#!/usr/bin/env sh
# fmt(1) wrapper script for prefixed text
# useful for comments (e.g., "//" prefix) and quotations (">" prefix)
set -u
command -v setpipefail >/dev/null && . "$(which setpipefail)"

usage() {
	echo "usage: $0 [-w width] [-p prefix]" 1>&$1
	echo "Wrap prefixed text at given column width (default 80)." 1>&$1
	echo "If prefix is unspecified, auto-detection is attempted." 1>&$1
	exit $(($1 - 1))
}

width=80
prefix=""
while getopts w:p:h name; do
	case $name in
	w) width=$OPTARG;;
	p) prefix="$OPTARG";;
	h) usage 1;;
	?) usage 2;;
	esac
done
shift $(($OPTIND - 1))

if [ $# -ne 0 ]; then
	echo "$0: unexpected arguments: $@" 1>&2
	usage 2
fi

# create a temporary file which is deleted on exit
tmpf="$(mktemp)"
[ $? -ne 0 ] && exit $?
trap 'rm -f -- "$tmpf"' EXIT

errchk() {
	ev=$?
	errmsg="$1"
	if [ $ev -ne 0 ]; then
		echo "$errmsg" 1>&2
		exit $ev
	fi
}

# dump stdin to the temporary file
cat >"$tmpf"
errchk "$0: error writing stdin into $tmpf, stopping"

# if prefix is unspecified, try to auto-detect it
if [ -z "$prefix" ]; then
	# first token on first line is taken as the prefix
	prefix="$(sed 1q "$tmpf" | awk '{ print $1 }')"
	errchk "$0: error reading first line of $tmpf, stopping"

	# Sanity check the prefix length.  Doxygen comments are "///" and
	# batch file comments are "rem", so allow prefixes <= 3 bytes; longer
	# prefixes could be allowed if there is a need.
	if [ ${#prefix} -gt 3 ]; then
		echo "$0: prefix \"$prefix\" is longer than expected" 1>&2
		exit 1
	fi
fi

# plan9port's fmt(1) and sed(1) aren't compatible with this script, so don't
# use them even if $PLAN9/bin is at the front of the path
fmt="$(no9 which fmt)"
sed="$(no9 which sed)"

$fmt --version 2>/dev/null | grep GNU >/dev/null
if [ $? -eq 0 ]; then
	# GNU coreutils fmt(1).  Unfortunately, when a line is indented with
	# tabs, GNU's fmt replaces spaces with tabs everywhere on the line:
	# e.g., two spaces after a period may become a tab.  Convert those tabs
	# back into spaces; then if (and only if) the line was indented with
	# tabs, convert the leading indentation back into tabs.
	ichar="$(sed 1q "$tmpf" | $sed 's/\(.\).*/\1/')"
	errchk "$0: error reading first character of $tmpf, stopping"
	postexpand=cat
	[ "$ichar" = "	" ] && postexpand="unexpand --first-only"
	$fmt --uniform-spacing --width=$width --goal=$width \
		--prefix="$prefix " <"$tmpf" | \
		expand | $postexpand
else
	# BSD fmt(1) has no --prefix, so the prefix must be removed
	# and re-added
	indent="$(sed 1q "$tmpf" | $sed 's/\([ 	]*\).*/\1/')"
	indentsp="$(echo "$indent" | expand)"
	newwidth=$(expr $width - ${#prefix} - ${#indentsp})
	if [ $newwidth -lt 0 ]; then
		echo "$0: combined indent and prefix too long for goal width ($width)" 1>&2
		echo "$0: indent.len=${#indentsp} prefix=\"$prefix\" prefix.len=${#prefix}" 1>&2
		exit 1
	fi
	cat "$tmpf" | \
		$sed "s@^$indent$prefix\( *\)@\1@" | \
		$fmt -s -w$newwidth | \
		$sed "s@^.@$indent$prefix @" | \
		$sed "s@^\$@$indent$prefix@"
fi
