#!/usr/bin/env sh
# alias for git add

# within Acme, if run without arguments, save and add current window
if [ $# -eq 0 -a "$samfile" != "" ]; then
	echo put | 9p write acme/$winid/ctl
	git add "$samfile"
	exit 0
fi

git add "$@"
